'use client'
import React, {useEffect, useState} from 'react';
import style from "./style.module.css";
import LoadingComponent from "@/components/ui-kit/Loading/LoadingComponent";
import Todos from "@/components/ui-kit/Todos/Todos";
import {Metadata} from "next";
import TodoSearch from "@/components/ui-kit/TodoSearch/TodoSearch";
import {getAllTodos} from "@/services/getAllTodos"

type todoType = {
    id :number;
    userId : number;
    title  : string;
    completed  : boolean;
}


// export const metadata: Metadata = {
//     title: 'todos',
//     description: 'Generated by create next app',
// }


const Page = () => {
    const [todos , setTodos] = useState<todoType[]|[]>([])
    const [isLoading , setIsLoading] = useState(true)
    useEffect(()=>{
        getAllTodos().then(data=>setTodos(data)).finally(()=>setIsLoading(false))
    },[])
    return (
        <div className={style.about}>
            <TodoSearch onSearch={setTodos} onLoading={setIsLoading}/>
            {
                isLoading
                    ?<LoadingComponent/>
                    :<Todos todos= {todos}/>
            }

        </div>
    );
};

export default Page;