import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div>
      hello
    </div>
  )
}
